# Generated by Django 3.1.2 on 2020-10-07 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('myuser_ptr', models.BooleanField(null=True)),
                ('permission_level', models.IntegerField(default=15)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
        ),
        migrations.CreateModel(
            name='SchoolUser',
            fields=[
            ],
            options={
                'verbose_name': 'Пользователь школы',
                'verbose_name_plural': 'Пользователи школ',
            },
            bases=('accounts.myuser',),
        ),
    ]
