# Generated by Django 3.1.2 on 2020-10-07 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluser',
            name='school',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
        ),
    ]
