# Generated by Django 3.1.2 on 2020-10-06 14:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permission',
            field=models.IntegerField(default=accounts.models.Permissions['school'].value),
        ),
    ]
