# Generated by Django 3.1.2 on 2021-01-28 04:39

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20210128_0439'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('permission', models.IntegerField(choices=[(1, 'Admin'), (5, 'Departament'), (10, 'District'), (15, 'School')])),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.myuser')),
            ],
            options={
                'verbose_name': 'Админ сайта',
                'verbose_name_plural': 'Админы сайта',
            },
            bases=('accounts.myuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentUser',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.myuser')),
            ],
            options={
                'verbose_name': 'Пользователь департамента',
                'verbose_name_plural': 'Пользователи департамента',
            },
            bases=('accounts.myuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolUser',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.myuser')),
                ('school', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
            options={
                'verbose_name': 'Пользователь школы',
                'verbose_name_plural': 'Пользователи школ',
            },
            bases=('accounts.myuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DistrictUser',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.myuser')),
                ('district', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.district')),
            ],
            options={
                'verbose_name': 'Пользователь района',
                'verbose_name_plural': 'Пользователи района',
            },
            bases=('accounts.myuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
