# Generated by Django 3.1.2 on 2020-10-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='permission',
            field=models.IntegerField(default=15),
        ),
    ]
