# Generated by Django 3.1.2 on 2020-10-07 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_schooluser_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='myuser_ptr',
        ),
        migrations.AddField(
            model_name='schooluser',
            name='myuser_ptr',
            field=models.OneToOneField(auto_created=True, default=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.myuser'),
            preserve_default=False,
        ),
    ]
