# Generated by Django 3.1.2 on 2020-10-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201008_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='permission_level',
            new_name='permission',
        ),
    ]
