# Generated by Django 3.1.2 on 2020-10-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201006_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooluser',
            name='permission_level',
        ),
    ]
