# Generated by Django 3.1.2 on 2020-10-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201008_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='permission',
            field=models.IntegerField(),
        ),
    ]
