# Generated by Django 3.1.2 on 2020-10-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_schooluser_permission_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooluser',
            options={'verbose_name': 'Пользователь школы', 'verbose_name_plural': 'Пользователи школ'},
        ),
    ]
