# Generated by Django 3.1.2 on 2020-10-10 12:59

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201009_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.myuser')),
            ],
            options={
                'verbose_name': 'Админ сайта',
                'verbose_name_plural': 'Админы сайта',
            },
            bases=('accounts.myuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentUser',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.myuser')),
            ],
            options={
                'verbose_name': 'Пользователь департамента',
                'verbose_name_plural': 'Пользователи департамента',
            },
            bases=('accounts.myuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
