# Generated by Django 3.1.2 on 2020-10-07 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_school_inn'),
        ('accounts', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='school',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='main.school'),
        ),
    ]
