# Generated by Django 3.1.1 on 2020-09-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.district')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
        migrations.CreateModel(
            name='Temperatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coolent_temp', models.IntegerField(blank=True, default=1)),
                ('air_temp', models.IntegerField(blank=True, default=15)),
                ('date', models.DateField(auto_now=True)),
                ('school', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
        ),
    ]
