# Generated by Django 3.1.2 on 2020-10-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='adress',
            field=models.CharField(default='', max_length=150),
        ),
    ]
