# Generated by Django 3.1.1 on 2020-09-26 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_school_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingConstructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Temperatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coolent_temp', models.IntegerField()),
                ('air_temp', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.CreateModel(
            name='BuildingsCharacters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_constructions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.buildingconstructions')),
                ('temperatures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.temperatures')),
            ],
        ),
    ]
