# Generated by Django 3.1.1 on 2020-10-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_district_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatures',
            name='coolent_temp',
            field=models.IntegerField(blank=True, default=15),
        ),
    ]
