# Generated by Django 3.1.2 on 2021-01-28 09:33

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210128_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingConstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blind_area_length', models.FloatField(blank=True, null=True, verbose_name='Длина отмостки')),
                ('blind_area_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип отмостки')),
                ('blind_area_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Состояние отмостки')),
                ('square', models.FloatField(blank=True, null=True, verbose_name='Площадь кровли')),
                ('roof_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип кровли')),
                ('roof_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал кровли')),
                ('roof_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Состояние кровли')),
                ('facade_square', models.FloatField(blank=True, null=True, verbose_name='Площадь фасада')),
                ('facade_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип фасада')),
                ('facade_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Состояние фасада')),
                ('window_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал окон')),
                ('energy_saving_window_percent', models.FloatField(blank=True, null=True, verbose_name='Процент энерго-сберегающих окон')),
                ('window_count', models.IntegerField(blank=True, null=True, verbose_name='Количество окон')),
                ('window_square', models.FloatField(blank=True, null=True, verbose_name='Площадь окон')),
                ('window_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Состояние окон')),
                ('inter_floor_overlapping_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал перекрытия')),
                ('inter_floor_overlapping_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Состояние перекрытия')),
                ('attic_overlapping_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал перекрытия')),
                ('attic_overlapping_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Состояние перекрытия')),
                ('attic_overlapping_warming', models.CharField(blank=True, max_length=50, null=True, verbose_name='Утепление')),
                ('basement_overlapping_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал перекрытия')),
                ('basement_overlapping_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Состояние перекрытия')),
            ],
            options={
                'verbose_name': 'Строительные конструкции',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='building_construction',
            field=annoying.fields.AutoOneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.buildingconstruction', verbose_name='Строительные конструкции'),
        ),
    ]
