# Generated by Django 3.1.2 on 2020-10-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201008_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='adress',
            field=models.CharField(default='', max_length=200),
        ),
    ]
