# Generated by Django 3.1.2 on 2021-01-28 09:36

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210128_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_construction',
            field=annoying.fields.AutoOneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.buildingconstruction', verbose_name='Строительные конструкции'),
        ),
    ]
