# Generated by Django 3.1.1 on 2020-09-26 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200926_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='building_characters',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.buildingscharacters'),
        ),
    ]
