# Generated by Django 3.1.1 on 2020-09-26 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_school_building_characters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='building_characters',
        ),
        migrations.AddField(
            model_name='school',
            name='building_constructions',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.buildingconstructions'),
        ),
        migrations.AddField(
            model_name='school',
            name='temperatures',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.temperatures'),
        ),
        migrations.DeleteModel(
            name='BuildingsCharacters',
        ),
    ]
