# Generated by Django 3.1.2 on 2020-10-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('build_number', models.CharField(max_length=50)),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='main.school')),
            ],
        ),
    ]
