# Generated by Django 3.1.2 on 2020-10-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_adress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Директор', 'verbose_name_plural': 'Директоры'},
        ),
    ]
