# Generated by Django 3.1.1 on 2020-09-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200926_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
