# Generated by Django 3.1.2 on 2021-02-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210201_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingconstruction',
            name='blind_area_square',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь отмостки'),
        ),
    ]
