# Generated by Django 3.1.2 on 2020-10-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201006_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='INN',
            field=models.CharField(default='', max_length=13),
        ),
    ]
