# Generated by Django 3.1.1 on 2020-09-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_district_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='building_constructions',
        ),
        migrations.RemoveField(
            model_name='school',
            name='temperatures',
        ),
    ]
