# Generated by Django 3.1.2 on 2021-02-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_buildingconstruction_blind_area_square'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingconstruction',
            name='attic_overlapping_thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='Толщина утепления'),
        ),
    ]
