# Generated by Django 3.1.2 on 2021-02-02 06:08

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210202_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='indoor_areas',
            field=annoying.fields.AutoOneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.indoorareas', verbose_name='Внутренние помещения'),
        ),
    ]
