# Generated by Django 3.1.2 on 2020-10-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201014_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Здание', 'verbose_name_plural': 'Здания'},
        ),
        migrations.DeleteModel(
            name='Temperatures',
        ),
    ]
