# Generated by Django 3.1.2 on 2021-02-02 09:26

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_building_indoor_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetySystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APS_installation_year', models.IntegerField(blank=True, null=True, verbose_name='Год установки АПС')),
                ('APS_and_SOUE_service_organization_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование обслуживающей организации (АПС и СОУЭ)')),
                ('price_for_APS_and_SOUE_per_year', models.FloatField(blank=True, null=True, verbose_name='Сумма на обслуживание АПС и СОУЭ в год (тыс. руб.)')),
                ('APS_modernization_year', models.IntegerField(blank=True, null=True, verbose_name='Год модернизации АПС')),
                ('APS_project', models.BooleanField(blank=True, null=True, verbose_name='Наличие проекта на АПС')),
                ('APS_compliance_with_the_project', models.BooleanField(blank=True, null=True, verbose_name='Соответствие проектной документации с установленной АПС')),
                ('APS_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вид АПС')),
                ('SOUE_installation_year', models.IntegerField(blank=True, null=True, verbose_name='Год установки СОУЭ')),
                ('SOUE_type', models.IntegerField(blank=True, null=True, verbose_name='Тип СОУЭ')),
                ('SOUE_project', models.BooleanField(blank=True, null=True, verbose_name='Наличие проекта на СОУЭ')),
                ('SOUE_compliance_with_the_project', models.BooleanField(blank=True, null=True, verbose_name='Соответствие проектной документации с установленной СОУЭ')),
                ('APS_and_SOUE_disadvantages', models.TextField(blank=True, null=True, verbose_name='Недостатки, прописанные в акте обслуживающей АПС и СОУЭ организации')),
                ('automatic_smoke_exhaust', models.BooleanField(blank=True, null=True, verbose_name='Наличие системы автоматического дымоудаления')),
                ('ASE_service_organization_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование обслуживающей организации (Система автоматического дымоудаления)')),
                ('price_for_ASE_per_year', models.FloatField(blank=True, null=True, verbose_name='Сумма на обслуживание системы автоматического дымоудаления в год (тыс. руб.)')),
                ('CCTV_installation_year', models.IntegerField(blank=True, null=True, verbose_name='Год установки системы видеонаблюдения')),
                ('CCTV_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вид системы видеонаблюдения')),
                ('CCTV_complies_safe_city_program', models.BooleanField(blank=True, null=True, verbose_name='Соответствует техническим требованиям программы «Безопасный город»')),
                ('indoor_cameras_count', models.IntegerField(blank=True, null=True, verbose_name='Количество камер внутри помещения')),
                ('outdoor_cameras_count', models.IntegerField(blank=True, null=True, verbose_name='Количество наружных камер')),
                ('CCTV_project', models.BooleanField(blank=True, null=True, verbose_name='Наличие проекта на систему видеонаблюдения')),
                ('CCTV_is_workable', models.BooleanField(blank=True, null=True, verbose_name='Техническое состояние системы видеонаблюдения')),
                ('unworkable_cameras_count', models.IntegerField(blank=True, null=True, verbose_name='Количество неисправных камер')),
            ],
            options={
                'verbose_name': 'Система безопасности',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='safety_system',
            field=annoying.fields.AutoOneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.safetysystem', verbose_name='Система безопасности'),
        ),
    ]
