# Generated by Django 3.1.2 on 2021-02-02 12:49

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210202_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritoryImprovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green_area_square', models.FloatField(blank=True, null=True, verbose_name='Площадь зеленых насаждений')),
                ('emergency_trees_count', models.IntegerField(blank=True, null=True, verbose_name='Количество аварийных деревьев, согласно порубочного талона')),
                ('asphalt_area', models.FloatField(blank=True, null=True, verbose_name='Площадь асфальтового покрытия')),
                ('asphalt_technical_condition', models.TextField(blank=True, null=True, verbose_name='Техническое состояние асфальтового покрытия ')),
                ('asphalt_percent_of_technical_condition_field', models.IntegerField(blank=True, null=True, verbose_name='Процент асфальтового покрытия, относящегося к полю технического состояния')),
                ('fence_volume', models.FloatField(blank=True, null=True, verbose_name='Объем ограждения')),
                ('fence_technical_condition', models.TextField(blank=True, null=True, verbose_name='Техническое состояние ограждения')),
                ('fence_volume_of_technical_condition_field', models.IntegerField(blank=True, null=True, verbose_name='Обьём ограждения, относящегося к полю технического состояния')),
                ('container_site', models.BooleanField(blank=True, null=True, verbose_name='Наличие контейнерной площадки')),
                ('container_site_material', models.TextField(blank=True, null=True, verbose_name='Материал покрытия контейнерной площадки')),
                ('container_site_square', models.FloatField(blank=True, null=True, verbose_name='Площадь контейнерной площадки')),
                ('container_site_fence', models.BooleanField(blank=True, null=True, verbose_name='Наличие ограждения контейнерной площадки')),
                ('total_container_volume', models.FloatField(blank=True, null=True, verbose_name='Суммарный объем контейнеров')),
            ],
            options={
                'verbose_name': 'Благоустройство территории',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='territory_improvement',
            field=annoying.fields.AutoOneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.territoryimprovement', verbose_name='Система безопасности'),
        ),
    ]
