# Generated by Django 3.1.2 on 2020-10-20 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_building_use_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.school', verbose_name='Школа'),
        ),
    ]
