# Generated by Django 3.1.2 on 2021-02-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210202_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indoorareas',
            name='admin_room_count_of_technical_condition_field',
        ),
        migrations.RemoveField(
            model_name='indoorareas',
            name='auditorium_percent_of_technical_condition_field',
        ),
        migrations.RemoveField(
            model_name='indoorareas',
            name='auditorium_technical_condition',
        ),
        migrations.RemoveField(
            model_name='indoorareas',
            name='bathroom_count_of_technical_condition_field',
        ),
        migrations.RemoveField(
            model_name='indoorareas',
            name='bathroom_technical_condition',
        ),
        migrations.RemoveField(
            model_name='indoorareas',
            name='classroom_count_of_technical_condition_field',
        ),
        migrations.RemoveField(
            model_name='indoorareas',
            name='classrooms_technical_condition',
        ),
        migrations.RemoveField(
            model_name='indoorareas',
            name='corridors_percent_of_technical_condition_field',
        ),
        migrations.RemoveField(
            model_name='indoorareas',
            name='corridors_technical_condition',
        ),
        migrations.RemoveField(
            model_name='indoorareas',
            name='emergency_exit_condition',
        ),
        migrations.RemoveField(
            model_name='indoorareas',
            name='emergency_exit_count_of_technical_condition_field',
        ),
        migrations.RemoveField(
            model_name='indoorareas',
            name='gym_percent_of_technical_condition_field',
        ),
        migrations.RemoveField(
            model_name='indoorareas',
            name='gym_technical_condition',
        ),
        migrations.RemoveField(
            model_name='indoorareas',
            name='pantry_count_of_technical_condition_field',
        ),
        migrations.RemoveField(
            model_name='indoorareas',
            name='pantry_technical_condition',
        ),
        migrations.RemoveField(
            model_name='territoryimprovement',
            name='asphalt_percent_of_technical_condition_field',
        ),
        migrations.RemoveField(
            model_name='territoryimprovement',
            name='asphalt_technical_condition',
        ),
        migrations.RemoveField(
            model_name='territoryimprovement',
            name='fence_technical_condition',
        ),
        migrations.RemoveField(
            model_name='territoryimprovement',
            name='fence_volume_of_technical_condition_field',
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='admin_room_emergency_status_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество административных помещений с аварийным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='admin_room_ok_status_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество административных помещений с работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='admin_room_warning_status_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество административных помещений с ограниченно работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='auditorium_emergency_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент актовых залов с аварийным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='auditorium_ok_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент актовых залов с работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='auditorium_warning_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент актовых залов с ограниченно работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='bathroom_emergency_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество санузлов с аварийным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='bathroom_ok_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество санузлов с работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='bathroom_warning_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество санузлов с ограниченно работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='classroom_emergency_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество учебных/игровых помещений с аварийным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='classroom_ok_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество учебных/игровых помещений с работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='classroom_warning_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество учебных/игровых помещений с ограниченно работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='corridors_emergency_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент коридоров с аварийным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='corridors_ok_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент коридоров с работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='corridors_warning_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент коридоров с ограниченно работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='emergency_exit_emergency_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество эвакуационных выходов с аварийным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='emergency_exit_ok_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество эвакуационных выходов с работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='emergency_exit_warning_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество эвакуационных выходов с ограниченно работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='gym_emergency_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент спортзалов с аварийным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='gym_ok_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент спортзалов с работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='gym_warning_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент спортзалов с ограниченно работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='pantry_emergency_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество буфетных с аварийным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='pantry_ok_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество буфетных с работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='indoorareas',
            name='pantry_warning_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество буфетных с ограниченно работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='territoryimprovement',
            name='asphalt_emergency_percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Процент асфальтового покрытия с аварийным состоянием'),
        ),
        migrations.AddField(
            model_name='territoryimprovement',
            name='asphalt_ok_percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Процент асфальтового покрытия с работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='territoryimprovement',
            name='asphalt_warning_percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Процент асфальтового покрытия с ограниченно работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='territoryimprovement',
            name='fence_emergency_volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Обьём ограждения с аварийным состоянием'),
        ),
        migrations.AddField(
            model_name='territoryimprovement',
            name='fence_ok_volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Обьём ограждения с работоспособным состоянием'),
        ),
        migrations.AddField(
            model_name='territoryimprovement',
            name='fence_warning_volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Обьём ограждения с ограниченно работоспособным состоянием'),
        ),
    ]
