# Generated by Django 3.1.2 on 2020-10-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201020_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='use_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Назначение здания'),
        ),
    ]
