# Generated by Django 3.1.7 on 2021-02-22 13:42

from django.db import migrations, models
import django.db.models.deletion
import main.models.DocumentsModel


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210203_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibleenvironment',
            name='bathroom_contrast_tape_on_the_steps',
            field=models.BooleanField(blank=True, null=True, verbose_name='Наличие контрастной ленты на ступенях (Санузел)'),
        ),
        migrations.AlterField(
            model_name='accessibleenvironment',
            name='bathroom_handrails_and_railings',
            field=models.BooleanField(blank=True, null=True, verbose_name='Наличие поручней и перил (Санузел)'),
        ),
        migrations.AlterField(
            model_name='accessibleenvironment',
            name='bathroom_sound_beacons',
            field=models.BooleanField(blank=True, null=True, verbose_name='Наличие звуковых маяков (кнопка вызова)(Санузел)'),
        ),
        migrations.AlterField(
            model_name='accessibleenvironment',
            name='bathroom_tactile_information_stand',
            field=models.BooleanField(blank=True, null=True, verbose_name='Наличие тактильного информационного стенда (Санузел)'),
        ),
        migrations.AlterField(
            model_name='accessibleenvironment',
            name='bathroom_tactile_tiles',
            field=models.BooleanField(blank=True, null=True, verbose_name='Наличие тактильной плитки (Санузел)'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_BTI', models.FileField(upload_to=main.models.DocumentsModel.inn_dir_path, verbose_name='Паспорт БТИ')),
                ('topographic_plan', models.FileField(upload_to=main.models.DocumentsModel.inn_dir_path, verbose_name='Топографический план')),
                ('teplosnabj_MK', models.FileField(upload_to=main.models.DocumentsModel.inn_dir_path, verbose_name='МК на теплоснабжение')),
                ('vodosnabj_MK', models.FileField(upload_to=main.models.DocumentsModel.inn_dir_path, verbose_name='МК на водоснабжение')),
                ('electrosnabj_MK', models.FileField(upload_to=main.models.DocumentsModel.inn_dir_path, verbose_name='МК на электроснабжение')),
                ('school', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Документы',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
