# Generated by Django 3.1.2 on 2020-10-21 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201020_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='use_type',
            new_name='purpose',
        ),
    ]
