# Generated by Django 3.1.7 on 2021-03-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210222_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='arend_square',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь зданий/помещений, сдаваемых в аренду'),
        ),
        migrations.AlterField(
            model_name='building',
            name='build_height',
            field=models.FloatField(blank=True, null=True, verbose_name='Высота здания'),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_square',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь здания'),
        ),
        migrations.AlterField(
            model_name='building',
            name='land_square',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь земельного участка'),
        ),
        migrations.AlterField(
            model_name='building',
            name='repair_need_square',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь, требующая ремонта'),
        ),
        migrations.AlterField(
            model_name='building',
            name='unused_square',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь неиспользуемых зданий/помещений м.кв'),
        ),
    ]
