# Generated by Django 3.1.2 on 2020-10-22 06:56

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201022_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='first_name',
            field=models.CharField(default='', max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='last_name',
            field=models.CharField(default='', max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='patronymic',
            field=models.CharField(default='', max_length=30, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='school',
            name='director',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.personal', verbose_name='Директор', null=True),
        ),
    ]
