# Generated by Django 3.1.2 on 2020-10-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20201022_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookkeeper',
            fields=[
                ('personal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.personal')),
            ],
            options={
                'verbose_name': 'Бухгалтер',
                'verbose_name_plural': 'Бухгалтеры',
            },
            bases=('main.personal',),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('personal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.personal')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководители',
            },
            bases=('main.personal',),
        ),
        migrations.CreateModel(
            name='ResponsibleForFilling',
            fields=[
                ('personal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.personal')),
            ],
            options={
                'verbose_name': 'Ответственный за заполнение',
                'verbose_name_plural': 'Ответственные за заполнение',
            },
            bases=('main.personal',),
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name': 'Персонал', 'verbose_name_plural': 'Персонал'},
        ),
        migrations.RemoveField(
            model_name='school',
            name='director',
        ),
        migrations.AddField(
            model_name='personal',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.school'),
        ),
    ]
