# Generated by Django 3.1.2 on 2020-10-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20201022_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='school',
        ),
        migrations.AddField(
            model_name='bookkeeper',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.school'),
        ),
        migrations.AddField(
            model_name='director',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.school'),
        ),
        migrations.AddField(
            model_name='responsibleforfilling',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.school'),
        ),
    ]
