# Generated by Django 3.1.2 on 2020-10-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20201024_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='address',
        ),
        migrations.AddField(
            model_name='building',
            name='street',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='building',
            name='street_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='school',
            name='edu_type',
            field=models.CharField(default='', max_length=20, verbose_name='Вид образования'),
        ),
        migrations.AddField(
            model_name='school',
            name='form_type',
            field=models.CharField(default='', max_length=20, verbose_name='Вид организационно-правовой формы'),
        ),
    ]
