# Generated by Django 3.1.2 on 2020-10-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20201025_0118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResponsibleForFilling',
            new_name='Updater',
        ),
        migrations.CreateModel(
            name='ZavHoz',
            fields=[
                ('personal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.personal')),
                ('school', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.school')),
            ],
            options={
                'verbose_name': 'Завхоз',
                'verbose_name_plural': 'Завхозы',
            },
            bases=('main.personal',),
        ),
    ]
