# Generated by Django 3.1.2 on 2020-10-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20201025_0130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Основные сведения', 'verbose_name_plural': 'Школы'},
        ),
    ]
