# Generated by Django 3.1.2 on 2020-10-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20201028_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(default='', max_length=300, verbose_name='Полное название'),
        ),
    ]
