# Generated by Django 3.1.2 on 2020-10-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20201028_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='first_name',
            field=models.CharField(default=None, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='last_name',
            field=models.CharField(default=None, max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='patronymic',
            field=models.CharField(default=None, max_length=30, verbose_name='Отчество'),
        ),
    ]
