# Generated by Django 3.1.2 on 2020-10-28 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20201028_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='school',
        ),
        migrations.AddField(
            model_name='bookkeeper',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.school'),
        ),
        migrations.AddField(
            model_name='director',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.school'),
        ),
        migrations.AddField(
            model_name='updater',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.school'),
        ),
        migrations.AddField(
            model_name='zavhoz',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.school'),
        ),
    ]
