# Generated by Django 3.1.2 on 2020-10-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20201028_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='email',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='personal',
            name='phone',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='Телефон'),
        ),
    ]
