# Generated by Django 3.1.2 on 2020-11-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20201028_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='school',
        ),
        migrations.AddField(
            model_name='school',
            name='director',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=models.SET_NULL, to='main.director', null=True),
        ),
    ]
