# Generated by Django 3.1.2 on 2020-11-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20201110_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='director',
            field=models.OneToOneField(auto_created=True, default=None, null=True, on_delete=models.SET(None), to='main.director'),
        ),
    ]
