# Generated by Django 3.1.2 on 2020-11-10 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20201110_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='director',
            field=models.OneToOneField(auto_created=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.director'),
        ),
    ]
