# Generated by Django 3.1.2 on 2020-11-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20201110_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='director',
        ),
    ]
