# Generated by Django 3.1.2 on 2020-11-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20201110_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='director',
        ),
        migrations.AddField(
            model_name='director',
            name='school',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.school'),
        ),
    ]
