# Generated by Django 3.1.2 on 2020-12-07 05:54

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20201110_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.building', verbose_name='Здание')),
            ],
            bases=(models.Model, main.models.MyModel),
        ),
    ]
