# Generated by Django 3.1.2 on 2020-12-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_temperature_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='temperature',
        ),
        migrations.AddField(
            model_name='temperature',
            name='air_temperature',
            field=models.FloatField(default=20, verbose_name='Температура воздуха'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='coolent_temperature',
            field=models.FloatField(default=20, verbose_name='Температура теплоносителя'),
            preserve_default=False,
        ),
    ]
