# Generated by Django 3.1.2 on 2020-12-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_auto_20201214_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='coolent_temperature',
            new_name='coolant_temperature',
        ),
    ]
