# Generated by Django 3.1.2 on 2021-01-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20210113_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='minimal_temperature',
        ),
    ]
