# Generated by Django 3.1.2 on 2021-01-27 04:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_remove_temperature_minimal_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_site', models.CharField(blank=True, max_length=100, null=True, verbose_name='Оффициальный сайт')),
                ('legal_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Юридический адрес')),
                ('formation_date', models.DateField(blank=True, default=django.utils.timezone.now, max_length=100, null=True, verbose_name='Дата образования юридического лица')),
                ('school', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.school', verbose_name='Школа')),
            ],
            bases=(models.Model, main.models.MyModel),
        ),
    ]
