# Generated by Django 3.1.2 on 2021-01-27 05:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_requisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='district',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.district', verbose_name='Территориальная принадлежность'),
        ),
        migrations.AlterField(
            model_name='requisites',
            name='formation_date',
            field=models.DateField(blank=True, default=datetime.date.today, max_length=100, null=True, verbose_name='Дата образования юридического лица'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
    ]
