from .admin_room import AdminRoom
from .auditorium import Auditorium
from .bathroom import Bathroom
from .classroom import Classroom
from .corridor import Corridor
from .emergency_exit import EmergencyExit
from .food_block import FoodBlock
from .gym import Gym
from .laundry import Laundry
from .pantry import Pantry
from .IndoorAreas import IndoorAreas
